<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
  /**
   * Find messages for chat
   */
  public function findOlderThan($id)
  {
    $query = $this->createQueryBuilder('m')
      ->where('m.id > :id')
      ->setParameter('id', $id)
      ->orderBy('m.id', 'DESC')
      ->setMaxResults(20)
      ->getQuery();
    $messages = $query->getResult(Query::HYDRATE_ARRAY);
    
    foreach($messages as &$message) {
      $message['date'] = $message['dateAdd']->format('Y-m-d H:i:s');
      unset($message['dateAdd']);
    }
    
    usort($messages, 'self::cmp_messages');
    
    return $messages;
  }

  /**
   * Sort array
   */  
  static public function cmp_messages($a, $b)
  {
    if ($a['id'] == $b['id']) {
        return 0;
    }
    
    return($a['id'] < $b['id']) ? -1 : 1;
  }
}
